---
# tasks file for install php-nginx-mysql

- name: CREATE NEW DIRECTORIES TO SERVER
  file:
    path: "{{ item }}" 
    state: directory
    owner: "{{ user }}"
    mode: '0775'
  loop:
    - ./docker/nginx
    - ./docker/php
    - ./docker/website
                  
- name: CREATE CONFIG FILES TO SERVER
  template:
    src: "files/{{ item.src }}"
    dest: "./docker/{{ item.dest }}"
  loop:
     - { src: 'nginx.conf.j2', dest: 'nginx/nginx.conf' }
     - { src: 'index.php.j2', dest: '/website/index.php' }
     - { src: '.env.j2', dest: '.env' }
     - { src: 'Dockerfile.j2', dest: '/php/Dockerfile' }    
     - { src: 'docker-compose.yml.j2', dest: '/docker-compose.yml' }  
                          
- name: RUN DOCKER-COMPOSE
  become: true
  shell: docker-compose up -d
  args:
    chdir: ./docker
  notify: RESTART NGINX
